Entity/MenuItem.php
<?php

namespace Easytek\EcmsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Easytek\EcmsBundle\Entity\MenuItem;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;
use Assetic\Exception\Exception;

/**
 * @ORM\Entity(repositoryClass="Easytek\EcmsBundle\Repository\MenuItemRepository")
 * @ORM\Table(name="ecms_menu_item")
 * @Gedmo\Tree(type="nested")
 */
class MenuItem extends NestedSetNode
{
    /**
     * @var integer $id
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string $uri
     *
     * @ORM\Column(name="uri", type="text", nullable=true)
     * @Assert\NotBlank
     * @Assert\Blank(groups={"rootMenuItem"})
     */
    private $uri;

    /**
     * @var string $name
     *
     * @ORM\Column(name="name", type="string", length=100)
     * @Assert\NotBlank
     */
    private $name;
    
    /**
     * @ORM\Column(name="role", type="string", length=50, nullable=true)
     * @var string
     */
    private $role;

    /**
     * @ORM\Column(name="lft", type="integer")
     * @Gedmo\TreeLeft
     */
    private $lft;

    /**
     * @ORM\Column(name="lvl", type="integer")
     * @Gedmo\TreeLevel
     */
    private $lvl;

    /**
     * @ORM\Column(name="rgt", type="integer")
     * @Gedmo\TreeRight
     */
    private $rgt;

    /**
     * @ORM\Column(name="root", type="integer", nullable=true)
     * @Gedmo\TreeRoot
     */
    private $root;

    /**
     * @Gedmo\TreeParent
     * @ORM\ManyToOne(targetEntity="MenuItem", inversedBy="children")
     * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", onDelete="SET NULL")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="MenuItem", mappedBy="parent")
     * @ORM\OrderBy({"lft" = "ASC"})
     */
    private $children;

    
    public function __construct()
    {
    	$this->children = new ArrayCollection();
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set uri
     *
     * @param string $uri
     */
    public function setUri($uri)
    {
        $this->uri = $uri;
		return $this;
    }

    /**
     * Get uri
     *
     * @return string 
     */
    public function getUri()
    {
        return $this->uri;
    }
    
    public function getRoute()
    {
    	if (!$this->hasRoute()) {
    		throw new \Exception('This MenuItem entity does not contain a route uri.');
    	}
    	
    	if ($this->hasJsonRoute()) {
    		return (array) json_decode($this->getUri());
    	} elseif ($this->hasRawRoute()) {
    		return array(
    			'name' => $this->getUri(),
    			'parameters' => array()
    		);
    	}
    	
    	throw new \Exception('Shouldn\'t happen :p');
    }
    
    private function hasJsonRoute()
    {
    	return preg_match('/^{/', $this->getUri());
    }
    
    private function hasRawRoute()
    {
    	return !$this->hasJsonRoute() && !preg_match('/(\/|#)/', $this->getUri());
    }
    
    public function hasRoute()
    {
    	return $this->hasJsonRoute() || $this->hasRawRoute();
    }
    
    public function getRouteName()
    {
    	$route = $this->getRoute();
   		return $route['name'];
    }
    
    public function getRouteParameters()
    {
      	$route = $this->getRoute();
   		return (array) $route['parameters'];
    }
    
    public function getHref($environment = 'prod')
    {
    	if ($environment != 'prod' && !preg_match('/^http/', $this->getUri())) {
    		return '/app_'.$environment.'.php'.$this->getUri();
    	} else {
    		return $this->getUri();
    	}
    }

    /**
     * Set name
     *
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
		return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $role
     */
    public function setRole($role)
    {
    	$this->role = $role;
    	return $this;
    }
    
    /**
     * @return string
     */
    public function getRole()
    {
    	return $this->role;
    }
    
   /**
    * Set lft
    *
    * @param integer $lft
    */
   public function setLft($lft)
   {
       $this->lft = $lft;
   }

   /**
    * Get lft
    *
    * @return integer 
    */
   public function getLft()
   {
       return $this->lft;
   }

   /**
    * Set lvl
    *
    * @param integer $lvl
    */
   public function setLvl($lvl)
   {
       $this->lvl = $lvl;
   }

   /**
    * Get lvl
    *
    * @return integer 
    */
   public function getLvl()
   {
       return $this->lvl;
   }

   /**
    * Set rgt
    *
    * @param integer $rgt
    */
   public function setRgt($rgt)
   {
       $this->rgt = $rgt;
   }

   /**
    * Get rgt
    *
    * @return integer 
    */
   public function getRgt()
   {
       return $this->rgt;
   }

   /**
    * Set root
    *
    * @param integer $root
    */
   public function setRoot($root)
   {
       $this->root = $root;
   }

   /**
    * Get root
    *
    * @return integer 
    */
   public function getRoot()
   {
       return $this->root;
   }

    /**
     * Set parent
     *
     * @param Easytek\EcmsBundle\Entity\MenuItem $parent
     */
    public function setParent(MenuItem $parent)
    {
        $this->parent = $parent;
    }

    /**
     * Get parent
     *
     * @return Easytek\EcmsBundle\Entity\MenuItem 
     */
    public function getParent()
    {
        return $this->parent;
    }
    
    public function getParentId()
    {
    	if ($this->getParent() !== null) {
    		return $this->getParent()->getId();
    	} else {
    		return null;
    	}
    }
    
    public function getParentName()
    {
        if ($this->getParent() !== null) {
    		return $this->getParent()->getName();
    	} else {
    		return null;
    	}
    }

    /**
     * Add children
     *
     * @param Easytek\EcmsBundle\Entity\MenuItem $child
     */
    public function addChild(MenuItem $child)
    {
        $this->children[] = $child;
		$child->setParent($this);
    }

    /**
     * Get children
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getChildren()
    {
        return $this->children;
    }
	
	public function getOptions()
	{
		return array('uri' => $this->getUri());
	}
	
	public function __toString()
	{
		return $this->getName();
	}
	
	public function toArray()
	{
		return array(
			'id' => $this->getId(),
			'name' => $this->getName(),
			'uri' => $this->getUri(),
		);
	}
}

Form/PageType.php
<?php

namespace Easytek\EcmsBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class PageType extends AbstractType
{
	/**
	 * @param FormBuilderInterface $builder
	 * @param array $options
	 */
	public function buildForm(FormBuilderInterface $builder, array $options)
	{
        $builder
            ->add('internalTitle', null, array(
				'attr' => array(
					'placeholder' => 'Titre interne de la page',
				)
			))
			// CKEditor n'est plus utilisé directement via le bundle, celui-ci ne permettant pas assez de configuration.
            ->add('html', 'textarea', array(
				'attr' => array(
					'class' => 'wysiwyg-page',
				)
			))
			->add('locale', 'choice', array(
				'label' => 'Langue',
				// TODO : définir la liste des langues en fonction de la conf
				'choices' => array( 
					'fr' => 'language.fr',
					'en' => 'language.en',
				) 
			))
            ->add('title', null, array(
                'label' => 'Titre de la fenêtre'
            ))
            ->add('description', null, array(
                'label' => 'Meta description'
            ))
            ->add('homepage', null, array(
                'label' => 'Marquer comme page d\'accueil'
            ))
        ;
	}

    public function getName()
    {
        return 'easytek_ecmsbundle_pagetype';
    }
}

Resources/views/Menu/adminDialogs.html.twig
<ul id="menu-dialogs" class="admin-dialogs">
	<li data-internal-uri="{{ path('ecms_menu_index') }}" rel="home">
		{% if menuItems is not empty %}
			{% include "EasytekEcmsBundle:Menu:indexDialog.html.twig" %}
		{% endif %}
	</li>

	{% for menuItem in menuItems if menuItem.lvl <= maxLevel %}
		<li data-internal-uri="{{ path('ecms_menu_new', {'parentId': menuItem.id}) }}" data-crud="create">
			{% set parentEntity = menuItem %}
			{% set form = newForms[menuItem.id] %}
			{% include "EasytekEcmsBundle:Menu:newDialog.html.twig" %}
		</li>
	{% endfor %}
	
	{% for entity in menuItems if entity.parent is not null %}
		<li data-internal-uri="{{ path('ecms_menu_edit', {'id': entity.id}) }}" data-crud="update">
			{% set form = editForms[entity.id] %}
			{% include "EasytekEcmsBundle:Menu:editDialog.html.twig" %}
		</li>
	{% endfor %}
</ul>

<script>
	globals.csrfTokens.menu = '{% render 'EasytekEcmsBundle:Menu:getCSRFToken' %}';
	globals.csrfTokens.menuSortable = '{% render 'EasytekEcmsBundle:MenuSortable:getCSRFToken' %}';
</script>

Resources/views/Menu/adminMenu.html.twig
{% for route in adminMenu %}
	<li>
		<a href="{{ path(route.name, route.parameters) }}">{{ route.humanName }}</a>
	</li>
{% endfor %}

Resources/views/Menu/edit.html.twig
{% extends app.request.isXmlHttpRequest ? "::base_ajax.html.twig" : "EasytekEcmsBundle::adminLayout.html.twig" %}

{% block content %}
	{% if menu is not empty %}
		<h2>Modification du menu : "{{ menu[0].name }}"</h2>
		
		<a href="{{ path('cms_menu_item_new', {'parentId' : menu[0].id}) }}" >Ajouter un élément à la racine du menu</a>
		
		<div id="menu-editable">
			{% import "EasytekEcmsBundle:Menu:treeBuilder.html.twig" as treeBuilder %}
			{{
				treeBuilder.root(menu[0], 'EasytekEcmsBundle:Menu:menuItemEdit.html.twig', 'ol', {
					'forceEmpty' : 'true',
					'depth' : 'null',
					'currentAsLink' : 'true',
					'currentClass' : 'current',
					'ancestorClass' : 'current_ancestor',
					'firstClass' : 'first',
					'lastClass' : 'last',
					'rootAttributes' : {'data-root-id' : menu[0].id},
					'csrf' : csrf
				})
			}}
		</div>
	{% else %}
		Racine introuvable.
	{% endif %}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	
	<script></script>
	
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js"></script>
	
	{% javascripts output='min/js/ecms_admin_menu_assets.js'
	    '@EasytekEcmsBundle/Resources/js/admin/jquery.ui.nestedSortable.js'
	    '@EasytekEcmsBundle/Resources/js/admin/menu.js'
	%}
	    <script type="text/javascript" src="{{ asset_url }}"></script>
	{% endjavascripts %}
{% endblock %}

Resources/views/Menu/editDialog.html.twig
<h2>Modifier l'élément de menu "{{ entity.name }}"</h2>
<div class="content">
 	{% include "EasytekEcmsBundle::notification.html.twig" %}
	
	{%
 		 include "EasytekEcmsBundle:Menu:form.html.twig"
		  with {
 			'action': path('ecms_menu_update', {'id': entity.id}),
 			'submit': 'Enregistrer',
 			'cancel': true,
 		  }
 	%}
</div>

Resources/views/Menu/editItem.html.twig
{% extends app.request.isXmlHttpRequest ? "::base_ajax.html.twig" : "EasytekEcmsBundle::adminLayout.html.twig" %}

{% block content %}
	<h1>Modifier l'élément de menu "{{ menuItem.name }}"</h1>
	
	{% include "EasytekEcmsBundle::notification.html.twig" %}
	
	{%
		 include "EasytekEcmsBundle:Menu:form.html.twig"
		  with {
			'action' : path('cms_menu_item_update', {'id': menuItem.id}),
			'submit' : 'Enregistrer',
		  }
	%}
	
	<ul class="record_actions">
		<li>
			<a href="{{ path('cms_menu_index') }}">Afficher le menu</a>
		</li>
	</ul>
{% endblock %}

Resources/views/Menu/form.html.twig
<form novalidate action="{{ action }}" method="post" {{ form_enctype(form) }}>
	{{ form_widget(form) }}
	<p>
		<button type="submit" class="btn">{{ submit }}</button>
		{% if cancel is defined and cancel %}
			<a href="{{ path('ecms_menu_index') }}" class="btn" rel="internal">Annuler</a>
		{% endif %}
	</p>
</form>

Resources/views/Menu/index.html.twig
{% extends app.request.isXmlHttpRequest ? "::base_ajax.html.twig" : "EasytekEcmsBundle::adminLayout.html.twig" %}

{% block content %}
	<ul class="actions">
		<li>
			<a href="{{ path('cms_menu_new') }}" class="btn btn-primary">Créer un nouveau menu</a>
		</li>
	</ul>

	<h2>Liste des menus</h2>

	{% if rootNodes is not empty %}
		<ul>
			{% for rootNode in rootNodes %}
				<li><a href="{{ path('cms_menu_edit', { 'rootId': rootNode.id }) }}">{{ rootNode.name }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		Aucun menu trouvé.
	{% endif %}
{% endblock %}

Resources/views/Menu/indexDialog.html.twig
<h2>Modification du menu</h2>

<div class="content">
	<a href="{{ path('ecms_menu_new', {'parentId' : menuItems[0].id}) }}" rel="internal">Ajouter un élément à la racine du menu</a>
	
	<div id="menu-editable">
		{% import "EasytekEcmsBundle:Menu:treeBuilder.html.twig" as treeBuilder %}
		{{
			treeBuilder.root(menuItems[0], 'EasytekEcmsBundle:Menu:menuItemEdit.html.twig', 'ol', {
				'forceEmpty': 'true',
				'depth': 'null',
				'currentAsLink': 'true',
				'currentClass': 'current',
				'ancestorClass': 'current_ancestor',
				'firstClass': 'first',
				'lastClass': 'last',
				'rootAttributes': {'data-root-id': menuItems[0].id},
				'csrf': csrf,
			})
		}}
	</div>
</div>

Resources/views/Menu/menuItemEdit.html.twig
<div class="item" data-id="{{ item.id }}" title="{{ item.id }}">
	<span class="deplacer"><img src="{{ asset('bundles/easytekecms/img/move.png') }}" alt="#" /></span>
	<span class="name">{{ item.name }}</span>
	<span class="actions">
		{% spaceless %}
			<a href="{{ path('cms_menu_item_edit', {'id' : item.id}) }}" title="Modifier cet élément de menu" rel="internal">
				<img src="{{ asset('bundles/easytekecms/img/link_edit.png') }}" alt="+" />
			</a>
		{% endspaceless %}
		{% spaceless %}
			<a href="{{ path('cms_menu_item_delete', {'id' : item.id, 'csrf' : options.csrf}) }}" class="delete" data-confirm="Êtes-vous certain de vouloir supprimer cet élément de menu ? Ses sous-éléments seront également supprimés.">
				<img src="{{ asset('bundles/easytekecms/img/delete.png') }}" alt="x" title="Supprimer cet élément de menu ainsi que ses enfants" />
			</a>
		{% endspaceless %}
		{% spaceless %}
			{% if options.depth > -2 %}
				<a href="{{ path('cms_menu_item_new', {'parentId' : item.id}) }}" rel="internal">
					<img src="{{ asset('bundles/easytekecms/img/add.png') }}" alt="@" title="Ajouter un sous-élément de menu à ''{{ item.name }}''" />
				</a>
			{% endif %}
		{% endspaceless %}
	</span>
</div>

Resources/views/Menu/new.html.twig
{% extends app.request.isXmlHttpRequest ? "::base_ajax.html.twig" : "EasytekEcmsBundle::adminLayout.html.twig" %}

{% block content %}
	<h2>Nouveau menu</h2>
	
	{% include "EasytekEcmsBundle::notification.html.twig" %}
	
	<form novalidate action="{{ path('cms_menu_create') }}" method="post" {{ form_enctype(form) }}>
		{{ form_widget(form) }}
		<p>
			<button type="submit" class="btn">Créer</button>
		</p>
	</form>
{% endblock %}

Resources/views/Menu/newDialog.html.twig
<h2>
	Ajouter un sous-élément
	{%- if parentEntity.id != 1 %}
		 de menu à "{{ parentEntity.name }}"
	{%- else %}
		à la racine du menu
	{%- endif %}
</h2>
<div class="content">
	{% include "EasytekEcmsBundle::notification.html.twig" %}
	
	{%
	 	include "EasytekEcmsBundle:Menu:form.html.twig"	
		with {
			'action': path('ecms_menu_create', {'parentId' :  parentEntity.id}),
			'submit': 'Créer',
			'cancel': true,
		} 
	%}
</div>

Resources/views/Menu/newItem.html.twig
{% extends app.request.isXmlHttpRequest ? "::base_ajax.html.twig" : "EasytekEcmsBundle::adminLayout.html.twig" %}

{% block content %}
	<h2>
		Ajouter un sous-élément
		{%- if parentEntity.id != 1 %}
			 de menu à "{{ parentEntity.name }}"
		{%- else %}
			à la racine du menu
		{%- endif %}
	</h2>
	
	{% include "EasytekEcmsBundle::notification.html.twig" %}
	
	{%
	 	include "EasytekEcmsBundle:Menu:form.html.twig"	
		with {
			'action': path('cms_menu_item_create', { 'parentId' :  parentEntity.id }),
			'submit':'Créer'
		} 
	 %}

	<ul class="record_actions">
		<li>
			<a href="{{ path('cms_menu_edit', { 'rootId': parentEntity.root }) }}">Afficher le menu</a>
		</li>
	</ul>
{% endblock %}

Resources/views/Menu/show.html.twig
{% if menu is empty %}
	!!! Erreur de menu : aucune racine !!! 
{% elseif menu|length == 1 %}
	!!! Menu vide !!!
{% else %}
	{% import "EasytekEcmsBundle:Menu:treeBuilder.html.twig" as treeBuilder %}
	{{
		treeBuilder.root(menu[0], 'EasytekEcmsBundle:Menu:menuItem.html.twig', 'ul', {
			'forceEmpty': 'true',
			'depth': 'null',
			'rootAttributes': {'class': 'nav'},
			'currentClass': 'active'
		})
	}}
{% endif %}

Resources/views/Menu/treeBuilder.html.twig
{% macro attributes(attributes) %}
	{% for name, value in attributes %}
		{%- if value is not none and value is not sameas(false) %}
			{{- ' %s="%s"'|format(name, value is sameas(true) ? name|e : value|e)|raw }}
		{%- endif %}
	{% endfor %}
{% endmacro %}

{% macro root(item, leafTemplate, rootType, options) %}
	{% if options.forceEmpty or (item.hasChildren and options.depth is not sameas(0)) %}
		<{{ rootType }}{% if options.rootAttributes is defined %}{{ _self.attributes(options.rootAttributes) }}{% endif %}>
			{{ _self.children(item, leafTemplate, rootType, options) }}
		</{{ rootType }}>
	{% endif %}
{% endmacro %}

{% macro children(item, leafTemplate, rootType, options) %}
	{# save current variables #}
	{% set currentOptions = options %}
	{% set currentItem = item %}

	{# update the depth for children #}
	{% if options.depth is not none %}
		{% set options = currentOptions|merge({'depth': currentOptions.depth - 1}) %}
	{% endif %}

	{% for item in currentItem.children %}
		{{ _self.item(item, leafTemplate, rootType, options) }}
	{% endfor %}

	{# restore current variables #}
	{% set item = currentItem %}
	{% set options = currentOptions %}
{% endmacro %}

{% macro item(item, leafTemplate, rootType, options) %}
	{% if item.role == '' or (app.user is not null and is_granted(item.role)) %}
		{# TODO : Gérer la ligne suivante au sein de MenuItem ? #}
		{% set isCurrent = app.request.requestUri == (item.hasRoute ? path(item.routeName, item.routeParameters) : item.uri) %}
		<li
			{% if isCurrent %}
				class="{% if options.currentClass is defined %}{{ options.currentClass }}{% else %}current{% endif %}"
			{% endif %}
		>
			{% include leafTemplate %}
			{%- if item.hasChildren and options.depth is not sameas(0) %}
				<{{ rootType }}>
					{{ _self.children(item, leafTemplate, rootType, options) }}
				</{{ rootType }}>
			{%- endif %}
		</li>
	{% endif %}
{% endmacro %}